import { Product, ProductCategory } from "@/lib/types";

// Vaqtinchalik namunaviy ma'lumot — DB ulanmasdan katalogni ko'rish uchun.
// Keyingi bosqichda Prisma orqali real bazadan olamiz.

export const CATEGORIES: { key: ProductCategory; label: string }[] = [
  { key: "portfolio", label: "Portfolio saytlar" },
  { key: "bot", label: "Botlar" },
  { key: "website", label: "Saytlar" },
  { key: "app", label: "Ilovalar" },
  { key: "code", label: "Kod bloklari" },
  { key: "uikit", label: "UI kitlar" },
];

// Ommaviy/keng qo'llaniladiganlari oldinda, kamroq ishlatiladiganlari orqada.
export const TECH_OPTIONS = [
  "React",
  "Next.js",
  "TypeScript",
  "Node.js",
  "PHP",
  "Python",
  "TailwindCSS",
  "Telegram",
  "Vue",
  "Flutter",
  "Laravel",
  "Django",
  "PostgreSQL",
  "MongoDB",
  "Docker",
  "Firebase",
  "React Native",
  "FastAPI",
  "AI / OpenAI",
  "GraphQL",
  "Redis",
  "NestJS",
  "Supabase",
  "Nuxt",
  "Svelte",
  "Angular",
  "Kotlin",
  "Swift",
  "Go",
  "Rust",
];

export const PRICE_RANGES = [
  { label: "$0 – $10", min: 0, max: 10 },
  { label: "$10 – $50", min: 10, max: 50 },
  { label: "$50 – $100", min: 50, max: 100 },
  { label: "$100 – $200", min: 100, max: 200 },
  { label: "$200 +", min: 200, max: Infinity },
];

export const PRODUCTS: Product[] = [
  {
    id: "1",
    title: "Telegram Do'kon Boti",
    slug: "telegram-shop-bot",
    price: 29,
    category: "bot",
    categoryLabel: "Telegram bot",
    badge: "TOP SOTUV",
    techStack: ["Python", "Telegram"],
    coverImage:
      "https://images.unsplash.com/photo-1611746872915-64382b5c76da?w=800&q=80",
    rating: 4.8,
    salesCount: 214,
    seller: "devbek",
  },
  {
    id: "2",
    title: "Next.js E-commerce Sayt",
    slug: "nextjs-ecommerce",
    price: 99,
    category: "website",
    categoryLabel: "To'liq sayt",
    subcategory: "other",
    badge: "YANGI",
    techStack: ["Next.js", "React", "TailwindCSS"],
    coverImage:
      "https://images.unsplash.com/photo-1467232004584-a241de8bcf5d?w=800&q=80",
    rating: 4.9,
    salesCount: 87,
    seller: "uxmaster",
  },
  {
    id: "3",
    title: "Flutter Yetkazib berish ilovasi",
    slug: "flutter-delivery-app",
    price: 149,
    category: "app",
    categoryLabel: "Mobil ilova",
    techStack: ["Flutter"],
    coverImage:
      "https://images.unsplash.com/photo-1512941937669-90a1b58e7e9c?w=800&q=80",
    rating: 5.0,
    salesCount: 42,
    seller: "mobiuz",
  },
  {
    id: "4",
    title: "React Admin Dashboard",
    slug: "react-admin-dashboard",
    price: 45,
    category: "code",
    categoryLabel: "Kod bloki",
    badge: "TOP SOTUV",
    techStack: ["React", "TailwindCSS"],
    coverImage:
      "https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=800&q=80",
    rating: 4.7,
    salesCount: 156,
    seller: "frontpro",
  },
  {
    id: "5",
    title: "AI Chat Bot (OpenAI)",
    slug: "ai-chat-bot",
    price: 79,
    category: "bot",
    categoryLabel: "AI bot",
    techStack: ["Node.js", "Telegram"],
    coverImage:
      "https://images.unsplash.com/photo-1677442136019-21780ecad995?w=800&q=80",
    rating: 4.9,
    salesCount: 98,
    seller: "ailab",
  },
  {
    id: "6",
    title: "Landing Page UI Kit",
    slug: "landing-ui-kit",
    price: 19,
    category: "uikit",
    categoryLabel: "UI kit",
    techStack: ["TailwindCSS", "React"],
    coverImage:
      "https://images.unsplash.com/photo-1545235617-9465d2a55698?w=800&q=80",
    rating: 4.6,
    salesCount: 320,
    seller: "pixelplug",
  },
  {
    id: "7",
    title: "Portfolio Sayt Shabloni",
    slug: "portfolio-template",
    price: 25,
    category: "website",
    categoryLabel: "Landing",
    subcategory: "portfolio",
    techStack: ["Next.js", "TailwindCSS"],
    coverImage:
      "https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=800&q=80",
    rating: 4.5,
    salesCount: 174,
    seller: "uxmaster",
  },
  {
    id: "8",
    title: "PHP Restoran Boshqaruvi",
    slug: "php-restaurant",
    price: 120,
    category: "website",
    categoryLabel: "CRM sayt",
    subcategory: "restaurant",
    techStack: ["PHP"],
    coverImage:
      "https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=800&q=80",
    rating: 4.4,
    salesCount: 61,
    seller: "backendboss",
  },
  {
    id: "9",
    title: "Instagram Auto-poster",
    slug: "instagram-autoposter",
    price: 35,
    category: "code",
    categoryLabel: "Skript",
    techStack: ["Python"],
    coverImage:
      "https://images.unsplash.com/photo-1611262588024-d12430b98920?w=800&q=80",
    rating: 4.3,
    salesCount: 129,
    seller: "devbek",
  },
];
