# Generated by Django 5.2.17 on 2026-10-09 04:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
        ('store', '0002_product_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='download_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Yuklab olishlar soni'),
        ),
        migrations.AddField(
            model_name='order',
            name='product_title',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Mahsulot nomi (snapshot)'),
        ),
        migrations.AlterField(
            model_name='order',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='store.product', verbose_name='Mahsulot'),
        ),
    ]
