# Generated by Django 5.2.17 on 2026-10-06 03:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Kategoriya nomi')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Slug')),
                ('icon', models.CharField(default='box', max_length=50, verbose_name='Ikonka nomi')),
            ],
            options={
                'verbose_name': 'Kategoriya',
                'verbose_name_plural': 'Kategoriyalar',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='Sarlavha')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Slug')),
                ('description', models.TextField(verbose_name='Batafsil tavsif')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Narxi (USD)')),
                ('subcategory', models.CharField(blank=True, max_length=50, null=True, verbose_name='Ichki toifa')),
                ('tech_stack', models.JSONField(blank=True, default=list, verbose_name='Texnologiyalar')),
                ('features', models.JSONField(blank=True, default=list, verbose_name="Xususiyatlar ro'yxati")),
                ('cover_image_file', models.ImageField(blank=True, null=True, upload_to='covers/', verbose_name='Muqova rasmi (fayl)')),
                ('cover_image_url', models.URLField(blank=True, max_length=500, null=True, verbose_name='Muqova rasmi (havola)')),
                ('screenshots', models.JSONField(blank=True, default=list, verbose_name='Skrinshotlar havolalari')),
                ('file_archive', models.FileField(blank=True, null=True, upload_to='products/archives/', verbose_name='Loyiha ZIP arxivi')),
                ('file_key', models.CharField(blank=True, max_length=255, null=True, verbose_name='Tashqi fayl kaliti')),
                ('demo_url', models.URLField(blank=True, null=True, verbose_name='Jonli demo havola')),
                ('telegram_username', models.CharField(blank=True, max_length=100, null=True, verbose_name="Sotuvchining Telegram username'i")),
                ('badge', models.CharField(blank=True, max_length=50, null=True, verbose_name='Belgi/Badge (masalan: TOP SOTUV)')),
                ('rating', models.FloatField(default=0.0, verbose_name='Reyting')),
                ('sales_count', models.PositiveIntegerField(default=0, verbose_name='Sotuvlar soni')),
                ('status', models.CharField(choices=[('DRAFT', "Qoralama (to'lov kutilmoqda)"), ('PENDING', 'Moderatsiyada'), ('ACTIVE', 'Faol (sotuvda)'), ('REJECTED', 'Rad etilgan'), ('PAUSED', "Vaqtincha to'xtatilgan")], default='DRAFT', max_length=20, verbose_name='Holati')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqti')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqti')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='store.category', verbose_name='Kategoriya')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to=settings.AUTH_USER_MODEL, verbose_name='Sotuvchi')),
            ],
            options={
                'verbose_name': 'Mahsulot',
                'verbose_name_plural': 'Mahsulotlar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=200, verbose_name='Sabab')),
                ('comment', models.TextField(blank=True, null=True, verbose_name="Qo'shimcha izoh")),
                ('status', models.CharField(choices=[('OPEN', "Ko'rib chiqilmagan"), ('RESOLVED', 'Hal qilingan')], default='OPEN', max_length=20, verbose_name='Holati')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Shikoyat vaqti')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='store.product', verbose_name='Mahsulot')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filed_reports', to=settings.AUTH_USER_MODEL, verbose_name='Shikoyat qiluvchi')),
            ],
            options={
                'verbose_name': 'Shikoyat',
                'verbose_name_plural': 'Shikoyatlar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(default=5, verbose_name='Baho (1-5)')),
                ('comment', models.TextField(verbose_name='Izoh matni')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yozilgan vaqti')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqti')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='store.product', verbose_name='Mahsulot')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Sharh',
                'verbose_name_plural': 'Sharhlar',
                'ordering': ['-created_at'],
                'unique_together': {('product', 'user')},
            },
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name="Qo'shilgan vaqti")),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlisted_by', to='store.product', verbose_name='Mahsulot')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlist_items', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Sevimlilar',
                'verbose_name_plural': 'Sevimlilar',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'product')},
            },
        ),
    ]
