# Generated by Django 5.2.17 on 2026-10-09 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name="O'chirilgan (arxiv)"),
        ),
    ]
