# Generated by Django 5.2.17 on 2026-10-06 03:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('store', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name="Summa (so'm)")),
                ('status', models.CharField(choices=[('PENDING', 'Kutilmoqda'), ('PAID', "To'landi"), ('FAILED', 'Bekor qilindi'), ('REFUNDED', 'Qaytarildi')], default='PENDING', max_length=20, verbose_name='Holati')),
                ('provider', models.CharField(blank=True, max_length=50, null=True, verbose_name="To'lov usuli (click, payme, balance)")),
                ('download_token', models.CharField(blank=True, max_length=64, null=True, unique=True, verbose_name='Yuklab olish xavfsiz tokeni')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqti')),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='Xaridor')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='store.product', verbose_name='Mahsulot')),
            ],
            options={
                'verbose_name': 'Buyurtma',
                'verbose_name_plural': 'Buyurtmalar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClickTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('PURCHASE', 'Mahsulot xaridi'), ('LISTING', "E'lon to'lovi")], max_length=20, verbose_name='Turi')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name="Summa (so'm)")),
                ('status', models.CharField(choices=[('PENDING', 'Kutilmoqda'), ('PAID', "To'landi"), ('FAILED', 'Bekor qilindi'), ('REFUNDED', 'Qaytarildi')], default='PENDING', max_length=20, verbose_name='Holati')),
                ('click_trans_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='Click Tranzaksiya ID')),
                ('merchant_trans_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='Merchant Tranzaksiya Param (masalan WSTP123)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqti')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name="To'langan vaqti")),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='listing_payments', to='store.product', verbose_name="Mahsulot (e'lon to'lovi uchun)")),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='click_transactions', to='orders.order', verbose_name='Buyurtma')),
            ],
            options={
                'verbose_name': 'Click Tranzaksiyasi',
                'verbose_name_plural': 'Click Tranzaksiyalari',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Withdrawal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name="Summa (so'm)")),
                ('card_number', models.CharField(max_length=30, verbose_name='Karta raqami (Uzcard/Humo)')),
                ('status', models.CharField(choices=[('PENDING', 'Kutilmoqda'), ('PAID', "To'landi"), ('REJECTED', 'Rad etildi')], default='PENDING', max_length=20, verbose_name='Holati')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name="So'rov vaqti")),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name="To'langan vaqti")),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='withdrawals', to=settings.AUTH_USER_MODEL, verbose_name='Sotuvchi')),
            ],
            options={
                'verbose_name': "Pul yechish so'rovi",
                'verbose_name_plural': "Pul yechish so'rovlari",
                'ordering': ['-created_at'],
            },
        ),
    ]
